# Copyright (C) 2011-2013 OpenStack Foundation
# Copyright 2013 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Meta-data for the build process
# DOCKER-NAME <%=@repo_name%>/<%=@blueprint_name%>:<%=@node%>
# DOCKER-VERSION <%=@VERSION%>
# build a puppet based image
FROM  <%=@base_image%>
MAINTAINER <%=@maintainer_name%>, <%=@maintainer_email%>

WORKDIR <%=@workspace_dir%>
ADD . <%=@workspace_dir%>

# setup so we can have a property that specifies the PROXY env when we docker_up it.
# Workaround set "nil" till we can find a way to unset ENV's
ENV PROXY "nil"
ENV http_proxy "nil"
ENV https_proxy "nil"
ENV HTTP_PROXY "nil"
ENV HTTPS_PROXY "nil"
ENV ftp_proxy "nil"
ENV socks_proxy "nil"
ENV no_proxy "nil"
ENV PUPPET_MODULES "/etc/puppet/modules:/opt/git/forj-oss/maestro/puppet/modules:/opt/git/forj-oss/redstone/puppet/modules"

COPY build/proxy_01.sh /etc/profile.d/
COPY runit.sh /etc/runit.sh
# Setup Minimal running system
RUN set -x -v; echo "docker operations for review"; lsb_release -a ; \
    [ -f /opt/workspace/build/build_00.sh ] && . /opt/workspace/build/build_00.sh;\
    . /etc/profile; \
    [ -f /etc/runit.sh ] && chmod a+x /etc/runit.sh; \
    cd /opt/git/forj-oss/redstone; \
    git reset --hard origin/master; \
    git pull origin master; \
    cd /opt/git/forj-oss/maestro; \
    git reset --hard origin/master; \
    git pull origin master; \
    apt-get update;

# bash /opt/git/forj-oss/maestro/hiera/hiera.sh

# custom docker commands
<%=@custom_commands%>


VOLUME [ "/data" ]

EXPOSE <%=@expose_ports%>

# TODO: test with entry points to learn how this works.
# ENTRYPOINT [ "/bin/bash", "-c", "/etc/runit.sh" ]
# CMD ["-l"]
